config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions' ,
    omniauth_callbacks: 'users/omniauth_callbacks'
    }
  # Facebook側で認証情報が挿入されると、再度リダイレクトしてアプリケーションのコールバックメソッドに戻ります。
  # コールバックを実装する場合に最初に必要なのは、config/routes.rbを開いて、Omniauthコールバックを実装するコールバックをDeviseに伝えることです
  
  root 'items#index'

  resources :users, only: [:index, :edit, :show, :update] do  

    collection do
      get 'logout' 
    end
    member do
      get 'item_management'
      get 'card'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :profiles, only: [:edit,:update]

  resources :addresses, only: [:edit,:update]
  # get ‘addresses/update’ => ‘addresses#update’

  resources :items do
  collection do
    get 'get_category_children', defaults: { format: 'json' }
    get 'get_category_grandchildren', defaults: { format: 'json' }
    get 'get_size', defaults: { format: 'json' }
    get 'get_shipping', defaults: { format: 'json' }
  end
  member do
    get 'get_category_children', defaults: { format: 'json' }
    get 'get_category_grandchildren', defaults: { format: 'json' }
    get 'get_size', defaults: { format: 'json' }
    get 'get_shipping', defaults: { format: 'json' }
    get 'buy', to: 'items#buy'
    get 'detail', to: 'detail'
    post 'pay', to: 'items#pay'
  end
end

  resources :signup do 
    collection do
      get 'top'
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' 
      get 'done'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validate :email_presence
  
  has_one :profile, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :items, dependent: :destroy

  has_one :card

  accepts_nested_attributes_for :profile
  accepts_nested_attributes_for :address

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable,
  :omniauthable, omniauth_providers: %i[facebook google_oauth2]
         
  validates :nickname, presence: true, length: { maximum: 20 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :nickname, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true,length: { minimum: 6 , maximum: 128 }

  def email_presence
    return if email.present?
    errors.add(:base, "このメールアドレスは既に使われております。")
  end

 # SNS認証 facebookとGoogleからuid,provider,email,などの値を受け取ってomniauth_callbacks_controller.rbにsessionとして送る。
 def self.find_oauth(auth)
  @user = User.where(uid: auth.uid, provider: auth.provider).first #userテーブルにprovider、uidがあったらログイン処理
            
    unless @user       
      @user = User.new(
                      uid: auth.uid,
                      provider: auth.provider,
                      nickname: auth.info.name,
                      email: auth.info.email,
                      password: Devise.friendly_token[0, 20],
                    )
    end
   return @user
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end
  
  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    provider = provider.to_s
    @user = User.find_oauth(request.env["omniauth.auth"])
  
    session[:uid] = @user.uid
    session[:provider] = @user.provider
    session[:nickname] = @user.nickname
    session[:email] = @user.email
    session[:password] = @user.password

    if @user.persisted?       #userが存在したら。
      sign_in_and_redirect @user, event: :authentication  #after_sign_in_path_forと同じ。（ログイン時実行されるメソッド、ログイン時に飛んでほしいページを指定）
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else    #userが存在しない場合
      redirect_to step1_signup_index_path
    end
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:index, :edit, :update, :logout, :show, :item_management, :card]

  def index
  end

  def edit
  end

  def show
    @parents = Category.where(ancestry: nil).limit(13)
  end

  def logout
    @parents = Category.where(ancestry: nil).limit(13)
  end

  def update
  end

  def item_management
    @items = current_user.items.order("created_at DESC")
  end

  def card
    card = Card.where(user_id: current_user.id)
    redirect_to card_index_path if card.exists?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_header.html.haml
.header
  .header-box
    .header-box__top 
      .logo-box
        = link_to image_tag("mercari.png",size: "132x35"), root_path
      .search-box
        %input.search-box__input-field{placeholder: '何かお探しですか？'}
        .serach-box__btn
          =fa_icon "search"
    .header-box__under
      %ul.header-box__under__left
        %li.category-box
          =fa_icon "list-ul"
          %span カテゴリーから探す
          .category_list
            .parents_list
              - @parents.each do |parent|
                = link_to "#{parent.name}", items_path(parent), class: "parent_category",id: "#{parent.id}"
            .children_list
            .grand_children_list
        %li.brand-box
          = image_tag "brand-logo.png", size: "18x13"
          %span ブランドから探す

      %ul.header-box__under__right

        %li.liked-items-link
          = link_to "#", class: "pc-header-menu-link" do
            = fa_icon "heart-o", class: :mypage_icon
            %span いいね！一覧

        %li.pc-header-user-nav
          = link_to "#", class: "pc-header-menu-link" do
            = fa_icon "bell-o", class: :mypage_icon
            %span お知らせ

        %li.sign-in-box
          = link_to "#", class: "pc-header-menu-link" do
            = fa_icon "check", class: :mypage_icon
            %span やることリスト

        %li.my-page-box
          = link_to  user_path(current_user.id), class: "pc-header-user-icon" do
            %figure
              =image_tag "user_icon.jpg", size: "32x32"
            %span マイページ

app/views/users/_side-bar.html.haml
.side-bar
  .side-bar-mypage-nav
    %ul.mypage-nav-list
      %li
        = link_to user_path(current_user.id), class: "mypage-nav-list-item active" do
          マイページ
          = fa_icon "chevron-right", class: :list_item_active

      %li
        = link_to "#", class: "mypage-nav-list-item" do
          お知らせ
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to "#", class: "mypage-nav-list-item" do
          やることリスト
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to "#", class: "mypage-nav-list-item" do
          いいね！一覧
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to new_item_path, class: "mypage-nav-list-item" do
          出品する
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to item_management_user_path(current_user.id), class: "mypage-nav-list-item" do
          出品した商品ー出品中
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to "", class: "mypage-nav-list-item" do
          出品した商品ー取引中
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to "#", class: "mypage-nav-list-item" do
          出品した商品ー売却済み
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to "#", class: "mypage-nav-list-item" do
          購入した商品ー取引中
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to "#", class: "mypage-nav-list-item" do
          購入した商品ー過去の取引
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to "#", class: "mypage-nav-list-item" do
          ニュース一覧
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to "#", class: "mypage-nav-list-item" do
          評価一覧
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to "#", class: "mypage-nav-list-item" do
          ガイド
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to "#", class: "mypage-nav-list-item" do
          お問い合わせ
          = fa_icon "chevron-right", class: :list_item

    %h3.mypage-nav-head メルペイ
    %ul.mypage-nav-list
      %li
        = link_to "#", class: "mypage-nav-list-item" do
          売上・振込申請
          = fa_icon "chevron-right", class: :list_item

      %li
        = link_to "#", class: "mypage-nav-list-item" do
          ポイント
          = fa_icon "chevron-right", class: :list_item

    %h3.mypage-nav-head 設定
    %ul.mypage-nav-list
      %li
        = link_to edit_profile_path(current_user.id), class: "mypage-nav-list-item" do
          プロフィール
          = fa_icon "chevron-right", class: :list_item

        %li
          = link_to "#", class: "mypage-nav-list-item" do
            発送元・お届け先住所変更
            = fa_icon "chevron-right", class: :list_item

        %li
          = link_to card_user_path(current_user.id), class: "mypage-nav-list-item" do
            支払い方法
            = fa_icon "chevron-right", class: :list_item

        %li
          = link_to "#", class: "mypage-nav-list-item" do
            メール/パスワード
            = fa_icon "chevron-right", class: :list_item

        %li
          = link_to edit_address_path(current_user.id), class: "mypage-nav-list-item" do
            本人情報
            = fa_icon "chevron-right", class: :list_item

        %li
          = link_to "#", class: "mypage-nav-list-item" do
            電話番号の確認
            = fa_icon "chevron-right", class: :list_item

        %li
          = link_to  logout_users_path, class: "mypage-nav-list-item" do
            ログアウト
            = fa_icon "chevron-right", class: :list_item

app/views/users/card.html.haml
= render partial: 'header'
%nav.bread-crumbs
  %ul
    %li.itemscope
      - breadcrumb :payment
      = render "layouts/breadcrumbs"
= render partial: 'items/exhibit_btn'
      
.l-container-clearfix
  .payment-method-box
    .payment-method-box__title
      支払い方法
    .payment-method-box__register
      .payment-method-box__register__title
        クレジットカード一覧
      .payment-method-box__register__btn
        =link_to 'クレジットカードを追加する', new_card_path, data: {"turbolinks" => false}
        = fa_icon 'credit-card'
      .payment-method-box__register__about
        =link_to '支払い方法について', '#'
        = fa_icon 'chevron-right'


  = render partial: 'users/side-bar'
= render partial: 'layouts/footer'

app/views/users/item_management.html.haml
= render partial: 'layouts/header'
%nav.bread-crumbs
  %ul
    %li.itemscope
      - breadcrumb :exhibiting
      = render "layouts/breadcrumbs"
= render partial: 'items/exhibit_btn'
        
.l-container-clearfix
  .mypage-item-management-tab
    .mypage-item-management-tab__title
      出品した商品

    %ul.mypage-item-management-tab__list
      %li.management_active
        =link_to "出品中", "#"
      %li
        =link_to "取引中", "#"
      %li
        =link_to "売却済み", "#"

    %ul.mypage-item-management-tab__item
    -unless @items.empty?
      -@items.each do |item|
        %li.mypage-item-list
          =link_to "", detail_item_path(item.id)
          =image_tag item.images[0].image.to_s
          .mypage-item-list__detail
            .mypage-item-list__detail__name
              = item.name
            .mypage-item-list__detail__status
              =fa_icon 'heart-o'
              .mypage-item-list__detail__status__like
                0
              =fa_icon 'comment-o'
              .mypage-item-list__detail__status__comment
                0
              .mypage-item-list__detail__status__display
                出品中
          .mypage-item-list__icon
            = fa_icon 'chevron-right'

    .mypage-item-management-history
      
      .mypage-item-management-history__prev
        =link_to "", '#'
        = fa_icon 'chevron-left'
      .mypage-item-management-history__next
        =link_to "", '#'
        = fa_icon 'chevron-right'

  = render partial: 'side-bar'
= render partial: 'layouts/footer'

app/views/users/logout.html.haml
= render partial: 'header'
%nav.bread-crumbs
  %ul
    %li.itemscope
      - breadcrumb :logout
      = render "layouts/breadcrumbs"

.logout-section
  = render partial: 'side-bar'
  .logout-content
    .logout-container
      .logout-inner
        = link_to destroy_user_session_path, method: :delete do
          .btn-logout{type: "submit"} ログアウト

= render partial: 'layouts/footer'

app/views/users/show.html.haml
= render partial: 'header'
%nav.bread-crumbs
  %ul
    %li.itemscope
      - breadcrumb :mypage
      = render "layouts/breadcrumbs"
= render partial: 'items/exhibit_btn'

.l-container-clearfix
  .mypage-content
    .mypage-content__user-icon
      = link_to "#" do
        %figure
          =image_tag "user_icon.jpg", size: "60x60"
        %h2 
        =current_user.nickname
        .mypage-content__user-icon__mypage-number
          %div
            評価
            %span.bold 0
          %div
            出品数
            %span.bold 0

    .mypage-content__tab-container-notification-todo
      %ul.mypage-content__tabs
        %li.active
          %h3
            = link_to "#mypage-tab-notification" do
              お知らせ
        %li
          %h3
            = link_to "#mypage-tab-todo" do
              やることリスト

      .tab-content
        %ul#mypage-tab-notification.mypage-content__item-list.mypage-content__tab-content__tab-pane.active
          %li
            = link_to "", class: "mypage-content__item-link" do
              %figure
                = image_tag "https://static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", alt: "data-src", class: "lazyload"
              .mypage-content__item-body
                .mypage-content__item-text 事務局から個別メッセージ「"1~2日で発送"を選択した商品は、40時間以上も早く売れています！」
                %time
                  %i.icon-time
                  %span 4 日前
              %i.icon-arrow-right
          %li
            = link_to "", class: "mypage-content__item-link" do
              %figure
                = image_tag "https://static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", alt: "data-src", class: "lazyload"
              .mypage-content__item-body
                .mypage-content__item-text 事務局から個別メッセージ「【重要】新サービス開始に伴う利用規約改訂のお知らせ」
                %time
                  %i.icon-time
                  %span 10 日前
              %i.icon-arrow-right
          %li.mypage-content__go-list
            = link_to "一覧を見る", ""
          
        %ul#mypage-tab-todo.mypage-content__item-list.mypage-content__tab-content__tab-pane
          %li.mypage-content__item-not-found.bold 現在、やることリストはありません

    .mypage-content__mypage-tab-container
      %h2.mypage-content__tab-head 購入した商品
      %ul.mypage-content__tabs
        %li.current
          %h3
            = link_to "#mypage-tab-transaction-now" do
              取引中
        %li
          %h3
            = link_to "#mypage-tab-transaction-old" do
              過去の取引
      .mypage-content__tab-content
        %ul#mypage-tab-transaction-now.mypage-content__item-list.mypage-content__tab-pane.active
          %li.mypage-content__item-not-found.bold 取引中の商品がありません

        %ul#mypage-tab-transaction-old.mypage-content__item-list.mypage-content__tab-pane
          %li.mypage-content__item-not-found.bold 過去に取引した商品がありません

  = render partial: 'side-bar'
= render partial: 'layouts/footer'