config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions' ,
    omniauth_callbacks: 'users/omniauth_callbacks'
    }
  # Facebook側で認証情報が挿入されると、再度リダイレクトしてアプリケーションのコールバックメソッドに戻ります。
  # コールバックを実装する場合に最初に必要なのは、config/routes.rbを開いて、Omniauthコールバックを実装するコールバックをDeviseに伝えることです
  
  root 'items#index'

  resources :users, only: [:index, :edit, :show, :update] do  

    collection do
      get 'logout' 
    end
    member do
      get 'item_management'
      get 'card'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :profiles, only: [:edit,:update]

  resources :addresses, only: [:edit,:update]
  # get ‘addresses/update’ => ‘addresses#update’

  resources :items do
  collection do
    get 'get_category_children', defaults: { format: 'json' }
    get 'get_category_grandchildren', defaults: { format: 'json' }
    get 'get_size', defaults: { format: 'json' }
    get 'get_shipping', defaults: { format: 'json' }
  end
  member do
    get 'get_category_children', defaults: { format: 'json' }
    get 'get_category_grandchildren', defaults: { format: 'json' }
    get 'get_size', defaults: { format: 'json' }
    get 'get_shipping', defaults: { format: 'json' }
    get 'buy', to: 'items#buy'
    get 'detail', to: 'detail'
    post 'pay', to: 'items#pay'
  end
end

  resources :signup do 
    collection do
      get 'top'
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' 
      get 'done'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :shipping
  belongs_to :size, optional: true
  belongs_to :category
  belongs_to :brand
  belongs_to :user
  accepts_nested_attributes_for :brand
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  #削除機能の実装に伴い一旦アソシエーションきってます
  # has_many :comments, dependent: :destroy
  # has_many :likes, dependent: :destroy
  # has_many :buyer_deals, class_name: 'Deal', foreign_key: :buyer_id, dependent: :destroy
  # has_many :seller_deals, class_name: 'Deal', foreign_key: :seller_id, dependent: :destroy
  # has_many :seller, class_name: 'User', foreign_key: :seller_id, through: :deals
  # has_many :buyer, class_name: 'User', foreign_key: :buyer_id, through: :deals

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :status, presence: true
  validates :prefecture, presence: true
  validates :fee, presence: true
  validates :arrival, presence: true
  validates :shipping_id, presence: true
  validates :category_id, presence: true
  validates :images, presence: true

  enum prefecture:{
    北海道:'北海道',青森県:'青森県',岩手県:'岩手県',宮城県:'宮城県',秋田県:'秋田県',山形県:'山形県',福島県:'福島県:',
    茨城県:'茨城県',栃木県:'栃木県',群馬県:'群馬県',埼玉県:'埼玉県',千葉県:'千葉県',東京都:'東京都',神奈川県:'神奈川県',
    新潟県:'新潟県',富山県:'富山県',石川県:'石川県',福井県:'福井県',山梨県:'山梨県',長野県:'長野県',
    岐阜県:'岐阜県',静岡県:'静岡県',愛知県:'愛知県',三重県:'三重県',
    滋賀県:'滋賀県',京都府:'京都府',大阪府:'大阪府',兵庫県:'兵庫県',奈良県:'奈良県',和歌山県:'和歌山県',
    鳥取県:'鳥取県',島根県:'島根県',岡山県:'岡山県',広島県:'広島県',山口県:'山口県',
    徳島県:'徳島県',香川県:'香川県',愛媛県:'愛媛県',高知県:'高知県',
    福岡県:'福岡県',佐賀県:'佐賀県',長崎県:'長崎県',熊本県:'熊本県',大分県:'大分県',宮崎県:'宮崎県',鹿児島県:'鹿児島県',沖縄県:'沖縄県'
  }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_parents, only: [:new, :create, :edit, :update]
  before_action :set_item, only: [:update, :edit, :buy, :show, :destroy, :detail, :pay]

  def index
    @items = Item.all.order("created_at DESC").includes(:images)
    @ledies_items = []
    @mens_items = []
    @camera_items = []
    @toy_items = []
    @items.each do |item|
      if Category.find(item.category_id).parent.parent.id == 1 && @ledies_items.length < 10
        @ledies_items << item
      elsif Category.find(item.category_id).parent.parent.id == 2 && @mens_items.length < 10
        @mens_items << item
      elsif Category.find(item.category_id).parent.parent.id == 8 && @camera_items.length < 10 
        @camera_items << item 
      elsif Category.find(item.category_id).parent.parent.id == 6 && @toy_items.length < 10
        @toy_items << item
      end
    end

    @chanel = []
    @louisvuitton = []
    @supreme = []
    @nike = []
    @items.each do |item|
      if item.brand.name == "シャネル" && @chanel.length < 10
        @chanel << item
      elsif item.brand.name == "ルイヴィトン" && @louisvuitton.length < 10
        @louisvuitton << item
      elsif item.brand.name == "シュプリーム" && @supreme.length < 10
        @supreme << item
      elsif item.brand.name == "ナイキ" && @nike.length < 10
        @nike << item
      end
    end

  end

  def new
    @item = Item.new
    @item.build_brand    #fields_forでbrandモデルに保存するための記述
    @item.images.build   #fields_forでimageモデルに保存するための記述
    @number = [0,1,2,3,4]
  end 

  # 親カテゴリーが選択された後に動くアクション(子)
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find(params[:parent_id]).children
  end

  # 子カテゴリーが選択された後に動くアクション(孫)
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  #孫カテゴリーが選択された後に動くアクション(サイズ)
  def get_size
    grandchild_id = Category.find(params[:grandchild_id]).id
        # 大人の洋服サイズ
    if grandchild_id.between?(36,95) || grandchild_id.between?(106,107) || grandchild_id.between?(204,218) || grandchild_id.between?(224,266) || grandchild_id.between?(289,292) || grandchild_id.between?(359,360)
      @sizes = Size.find(1).children
        # 女性の靴サイズ
    elsif grandchild_id.between?(96,104)
      @sizes = Size.find(2).children
        # 男性の靴サイズ
    elsif grandchild_id.between?(268,274)
      @sizes = Size.find(3).children
        # キッズの洋服小サイズ
    elsif grandchild_id.between?(364,389)
      @sizes = Size.find(4).children
        # キッズの洋服大サイズ
    elsif grandchild_id.between?(391,429)
      @sizes = Size.find(5).children
        # キッズの靴サイズ
    elsif grandchild_id.between?(431,434)
      @sizes = Size.find(6).children
    end
  end

  #配送料の負担項目が選択された後に動くアクション(配送の方法)
  def get_shipping
    #選択された配送料の負担(送料込みor着払い)に紐づく子カテゴリーの配列を取得
    @shipping_children = Shipping.find(params[:fee_id]).children
  end



  def create
    @item = Item.new(item_params)
    if @item.save!
      redirect_to root_path
    else
      redirect_to new_item_path
    end
  end

  
  
  def edit
    if @item.user.id == current_user.id && @item.product_status == nil
      @parent = Category.find(@item.category_id).parent.parent.id
      @child = Category.find(@item.category_id).parent.parent.children
      @grand_child = Category.find(@item.category_id).parent.children
      @shipping = Shipping.find(@item.shipping_id).parent.children
      @shipping_select = Shipping.find(@item.shipping_id)
      @images =  @item.images
      if @item.size_id != nil
      @size = Size.find(@item.size_id).parent.children
      @select_size = Size.find(@item.size_id)
      else
        return
      end
    else
      redirect_to root_path
    end
  end

  def update
    if @item.user_id == current_user.id && @item.product_status == nil

      if params[:images_id] != nil #パラメーターでimages_idが送られてきたら
        if params[:images_id].length == @item.images.length
          redirect_to edit_item_path(@item.id)
        else
          remove_images_at_index(params[:images_id])
        end
      else
        if @item.update!(item_params)
          redirect_to root_path
        else
          render :edit
        end
      end

    else
      redirect_to root_path
    end
  end

  def detail
    # unless @item.user == current_user
    #   redirect_to root_path
    # end
  end

  def destroy
    if @item.user.id == current_user.id
      @item.destroy
      redirect_to item_management_user_path(current_user.id)
    else
      redirect_to root_path , alert: '削除できません'
    end
  end

  def show
    @items = Item.all
    index=[]
    @items.each_with_index do |item, i|
      if @item.id == item.id
        index << i
      end
    end
    @nav_next = @items.slice(index[0] + 1, 1)
    @nav_prev = @items.slice(index[0] - 1, 1)

    @user_items = @item.user.items
    @category_items = Item.where(category_id: @item.category_id)
  end

  require 'payjp'

  def buy
    @address = current_user.address
    if @item.user_id == current_user.id || @item.product_status != nil
      redirect_to root_path
    else
      
      @card = Card.find_by(user_id: current_user.id)
      if @card.blank?
        session[:id] = params[:id]
      else
        #Cardテーブルは前回記事で作成、テーブルからpayjpの顧客IDを検索
        Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
        #保管した顧客IDでpayjpから情報取得
        customer = Payjp::Customer.retrieve(@card.customer_id)
        #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
        @default_card_information = customer.cards.retrieve(@card.card_id)
      end
    end
  end

  def pay
    
    if @item.product_status == nil && @item.user.id != current_user.id
      card = Card.find_by(user_id: current_user.id)
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      Payjp::Charge.create(
      :amount => @item.price.to_s, #支払金額を入力（itemテーブル等に紐づけても良い）
      :customer => card.customer_id, #顧客ID
      :currency => 'jpy', #日本円
      )
      
      @item.product_status = current_user.id.to_i
      @item.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def remove_images_at_index(index)
    remain_images = @item.images # 画像の配列をコピーする

    index.each do |index| #パラメータデー送られてきたimages_idの配列をeachで回す
      index = index.to_i #images_idはstring型なのでinteger柄に変換
      deleted_image = remain_images[index].delete #配列の位置を指定して削除
      deleted_image.try(:remove!)  # S3から削除する場合追加
    end

  end


  def item_params
    params.require(:item).permit(:name, :price, :description, :status, :prefecture, :fee, :arrival, :category_id, :size_id,:shipping_id,:product_status,:brand_id,
    brand_attributes: [:id, :name],
    images_attributes: [:id, :image]).merge(user_id: current_user.id)
  end

  def set_parents
    #実装の都合上メソッドにしてbefore_actionで呼び出している
    @parents = Category.all.order("id ASC").limit(13)
    @fees = [{id: 1, fee: "送料込み(出品者負担)"}, {id: 2, fee: "着払い(購入者負担)"}]
    @sizes = Size.all
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_exhibit_btn.html.haml
.exhibit-btn
  .exhibit-btn__box
    %p 出品
    .exhibit-btn-icon
      =link_to new_item_path do
        =fa_icon "camera"

app/views/items/_exhibition_footer.html.haml
.exhibition-footer
  %ul
    %li=link_to 'プライバシーポリシー', 'https://www.mercari.com/jp/privacy/'
    %li=link_to 'メルカリ利用規約', 'https://www.mercari.com/jp/tos/'
    %li=link_to '特定商取引に関する表記', 'https://www.mercari.com/jp/tokutei/'
  =image_tag "exhibition-footer-logo.png", class: "exhibition-footer-logo"
  %p © 2019 Mercari

app/views/items/_header.html.haml
.header
  .header-box
    .header-box__top 
      .logo-box
        =link_to "", items_path
        = image_tag "mercari.png",size: "132x35"
      .search-box
        %input.search-box__input-field{placeholder: '何かお探しですか？'}
        .serach-box__btn
          =fa_icon "search"
    - if user_signed_in?
      .header-box__under
        %ul.header-box__under__left
          %li.category-box
            =fa_icon "list-ul"
            %span カテゴリーから探す
          %li.brand-box
            = image_tag "brand-logo.png", size: "18x13"
            %span ブランドから探す
  
        %ul.header-box__under__right
  
          %li.pc-header-user-nav
            = link_to "#", class: "pc-header-menu-link" do
              = fa_icon "bell-o", class: :mypage_icon
              %span お知らせ
  
          %li.sign-in-box
            = link_to "#", class: "pc-header-menu-link" do
              = fa_icon "check", class: :mypage_icon
              %span やることリスト
  
          %li.my-page-box
            = link_to user_path(current_user.id), class: "pc-header-user-icon" do
              %figure
                =image_tag "user_icon.jpg", size: "32x32"
              %span マイページ
    - else
      .header-box__under
        %ul.header-box__under__left
          %li.category-box
            =fa_icon "list-ul"
            %span カテゴリーから探す
          %li.brand-box
            = image_tag "brand-logo.png", size: "18x13"
            %span ブランドから探す
        %ul.header-box__under__right
          %li.sign-in-box
            .sign-in-box__btn
              =link_to '新規会員登録', step1_signup_index_path
          %li.log-in-box
            .log-in-box__btn
              =link_to 'ログイン', '#'

app/views/items/_items.html.haml
%li.items-list-image
  .items-box
    =link_to "", item_path(items.id)
    .images-box-image
      =link_to "", item_path(items.id)
      .image-box-price
        %p
          ¥
          = items.price.to_s(:delimited)
      - items.images.each_with_index do |image, i|
      - break if i == 1
        =image_tag image.image.to_s
    .image-box-name
      %p=items.name
  -unless items.product_status == nil
    = render partial: 'sold_out2'

app/views/items/_sold_out.html.haml
.item-show-main-sold-out
  %p SOLD

app/views/items/_sold_out2.html.haml
.item-sold-out
  %p SOLD

app/views/items/buy.html.haml
.exhibition-wrapper
  .exhibition-header
    = image_tag "mercari.png",size: "185x49"
  .exhibition-field
    .exhibition-field__content
      .exhibition-field__content__inner
        .exhibition-title
          %h1 購入内容の確認
          .exhibition-buy-content
            - @item.images.each_with_index do |image, i|
            - break if i == 1
              =image_tag image.image.to_s
            .exhibition-buy-item
              .exhibition-buy-item__name
                = @item.name
              .exhibition-buy-item__price
                %span
                  ¥
                  = @item.price.to_s(:delimited)
                .exhibition-buy-item__price__shipping
                  -if @item.shipping_id.between?(3,11)
                    (税込)送料込み
                  - elsif @item.shipping_id.between?(12,15)
                    (税込)着払い
          .exhibition-buy-content
            .exhibition-buy-content__inner
              .buy-price-table
                .buy-price-table__title
                  %p 支払い金額
                .buy-price-table__price
                  ¥
                  = @item.price.to_s(:delimited)
              .buy-accordion-table
                .buy-accordion-table__check
                  %label
                    %input{type: 'checkbox'}
                    .point-check-button
                    %p
                      ポイントを使用(所持ポイント:P0)

                %ul.buy-accordion__parent
                  %li.buy-accordion__child
                    %label
                      %input{ name: "consume_point_radio", type: "radio", value: "all", id: 'point'}
                      .point-radio-button
                      %p
                        すべてのポイントを使う
                        %br
                        (使用ポイント:P0)
                  %li.buy-accordion__child
                    %label
                      %input{ name: "consume_point_radio", type: "radio", value: "all", id: 'point'}
                      .point-radio-button
                      %p
                        一部のポイントを使う
                  %li.buy-accordion__child2
                    %input{type: "number", placeholder: '使うポイントを入力'}

              .buy-info-table
                .buy-info-table__title
                  %p 支払い方法
                .buy-info-table__info
                  -if @card.blank?
                    = fa_icon 'plus-circle'
                    %span
                      =link_to '登録してください', new_card_path, data: {"turbolinks" => false}
                  - else
                    %p クレジットカード
                    .buy-info-table__info__num
                      = "**** **** **** " + @default_card_information.last4
                    .buy-info-table__info__expiration
                      有効期限
                      - exp_month = @default_card_information.exp_month.to_s
                      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                      = exp_month + " / " + exp_year
                    = image_tag "visa.png"
              .buy-info-table
                .buy-info-table__title
                  %p 配送先
                .buy-info-table__info
                -if @address.blank?
                  = fa_icon 'plus-circle'
                  %span
                    =link_to '登録してください', '#'
                -else
                  %p 
                    〒
                    =@address.zip_code
                    %br
                      =@address.prefecture
                      =@address.city
                      =@address.block
                      -if @address.building
                        =@address.building
                      %br
                        =current_user.profile.family_name
                        =current_user.profile.first_name
              .buy-button-table
                .buy-button-table__button 
                -unless @item.user.id == current_user.id
                  = form_tag(action: :pay, method: :post, disabled: :disabled) do
                    -if @card.blank? || @address.blank?
                      %button{:disabled => "disabled"} 購入する
                    -else
                      %button{:style => "background-color : #ea352d; cursor: pointer"} 購入する

  = render partial: 'items/exhibition_footer'

app/views/items/detail.html.haml
= render partial: 'layouts/header'
%nav.bread-crumbs
  %ul
    %li.itemscope
      - breadcrumb :product
      = render "layouts/breadcrumbs"
= render partial: 'items/exhibit_btn'
.item-detail-content
  .item-detail-content__box
    .item-show-content__box
      %h1.item-show-name
        =@item.name
      .item-show-main
        .item-show-main__photo
          .item-show-main__photo__big
            -@item.images.each_with_index do |image, i|
              -if i == 0
                .image-slide.image-active
                  =image_tag image.image.url
              -else
                .image-slide
                  =image_tag image.image.url
          .item-show-main__photo__small
            -@item.images.each_with_index do |image, i|
              -if i == 0
                .image-slide-prev.image-opacity
                  =image_tag image.image.url
              -else
                .image-slide-prev
                  =image_tag image.image.url
        %ul.item-show-main__detail
          %li.item-detail-table
            .item-detail-table__title
              出品者
            .item-detail-table__link
              =@item.user.nickname
              .item-user-rate
                = fa_icon 'smile-o'
                0
                = fa_icon 'meh-o'
                0
                = fa_icon 'frown-o'
                0

          %li.item-detail-table
            .item-detail-table__title
              カテゴリー
            .item-detail-table__link
              =@item.category.parent.parent.name
              %br
              = fa_icon 'chevron-right'
              =@item.category.parent.name
              %br
              = fa_icon 'chevron-right'
              =@item.category.name

          %li.item-detail-table
            .item-detail-table__title
              ブランド
            .item-detail-table__link
              =@item.brand.name

          %li.item-detail-table
            .item-detail-table__title
              商品のサイズ
            .item-detail-table__val
              -if @item.size == nil
                =''
              -else
                =@item.size.size


          %li.item-detail-table
            .item-detail-table__title
              商品の状態
            .item-detail-table__val
              =@item.status

          %li.item-detail-table
            .item-detail-table__title
              配送料の負担
            .item-detail-table__val
              -if @item.fee == 1
                送料込み(出品者負担)
              -else 
                着払い(購入者負担)

          %li.item-detail-table
            .item-detail-table__title
              配送料の方法
            .item-detail-table__val
              =@item.shipping.shipping

          %li.item-detail-table
            .item-detail-table__title
              配送元地域
            .item-detail-table__val
              =@item.prefecture

          %li.item-detail-table
            .item-detail-table__title
              配送日の目安
            .item-detail-table__val
              =@item.arrival

      .item-show-price
        .item-show-price__price
          ¥
          = @item.price
        .item-show-price__tax
          (税込)
        .item-show-price__fee
          -if @item.fee == 1
            送料込み
          -else 
            着払い

    .item-detail-content__change-box
      -if @item.user.id == current_user.id
        .item-detail-content__change-box__edit
          =link_to "商品の編集", edit_item_path(@item.id)
        %p or
        %button 出品を一旦停止する
        .item-detail-content__change-box__delete
          = link_to 'この商品を削除する', item_path(@item.id), method: :delete, data: { confirm: '本当に削除しますか？' }

    .item-show-content__comment
      .item-show-comment
        %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %textarea
        .item-show-comment__button
          コメントする


= render partial: 'layouts/footer'

app/views/items/show.html.haml
= render partial: 'layouts/header'

.item-show-content
  .item-show-content__box
    %h1.item-show-name
      =@item.name
    .item-show-main
      .item-show-main__photo
        .item-show-main__photo__big
          -@item.images.each_with_index do |image, i|
            -if i == 0
              .image-slide.image-active
                =image_tag image.image.url
            -else
              .image-slide
                =image_tag image.image.url
        .item-show-main__photo__small
          -@item.images.each_with_index do |image, i|
            -if i == 0
              .image-slide-prev.image-opacity
                =image_tag image.image.url
            -else
              .image-slide-prev
                =image_tag image.image.url
        -unless @item.product_status == nil
          = render partial: 'sold_out'
      %ul.item-show-main__detail
        %li.item-detail-table
          .item-detail-table__title
            出品者
          .item-detail-table__link
            =@item.user.nickname
            .item-user-rate
              = fa_icon 'smile-o'
              0
              = fa_icon 'meh-o'
              0
              = fa_icon 'frown-o'
              0

        %li.item-detail-table
          .item-detail-table__title
            カテゴリー
          .item-detail-table__link
            =@item.category.parent.parent.name
            %br
            = fa_icon 'chevron-right'
            =@item.category.parent.name
            %br
            = fa_icon 'chevron-right'
            =@item.category.name

        %li.item-detail-table
          .item-detail-table__title
            ブランド
          .item-detail-table__link
            =@item.brand.name

        %li.item-detail-table
          .item-detail-table__title
            商品のサイズ
          .item-detail-table__val
            -if @item.size == nil
              =''
            -else
              =@item.size.size


        %li.item-detail-table
          .item-detail-table__title
            商品の状態
          .item-detail-table__val
            =@item.status

        %li.item-detail-table
          .item-detail-table__title
            配送料の負担
          .item-detail-table__val
            -if @item.fee == 1
              送料込み(出品者負担)
            -else 
              着払い(購入者負担)

        %li.item-detail-table
          .item-detail-table__title
            配送料の方法
          .item-detail-table__val
            =@item.shipping.shipping

        %li.item-detail-table
          .item-detail-table__title
            配送元地域
          .item-detail-table__val
            =@item.prefecture

        %li.item-detail-table
          .item-detail-table__title
            配送日の目安
          .item-detail-table__val
            =@item.arrival

    .item-show-price
      .item-show-price__price
        ¥
        = @item.price
      .item-show-price__tax
        (税込)
      .item-show-price__fee
        -if @item.fee == 1
          送料込み
        -else 
          着払い
    -if user_signed_in?
      -if @item.user_id == current_user.id
        
      -elsif @item.product_status == nil
        .item-show-point
          .item-show-point__message 
            P0をお持ちです
        .item-show-buy-btn
          =link_to "購入画面に進む",buy_item_path(@item.id)
        .item-show-app
          =link_to "アプリで購入", "http://app.adjust.io/xio2ii?campaign=android&adgroup=items.buy_button1"
      -elsif @item.product_status != nil
        .item-show-buy-btn{ style: "color:white; background-color:#888; cursor: not-allowed;" } 
          売り切れました
    -else
      -if @item.product_status == nil
        .item-show-buy-btn
          =link_to "購入画面に進む",buy_item_path(@item.id)
        .item-show-app
          =link_to "アプリで購入", "http://app.adjust.io/xio2ii?campaign=android&adgroup=items.buy_button1"
      -else
        .item-show-buy-btn{ style: "color:white; background-color:#888; cursor: not-allowed;" } 
          売り切れました

      
    .item-show-description
      %p=@item.description

    .item-show-btn-content
      .item-show-btn-content__left
        %button.item-like-btn
          =fa_icon 'heart-o'
          いいね! 0
        .item-report-btn
          =fa_icon 'flag-o'
          不適切な商品の報告
      .item-show-btn-content__right
        =link_to "あんしん・あんぜんへの取り組み", "https://www.mercari.com/jp/safe/description/"

  .item-show-content__comment
    .item-show-comment
      %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      %textarea
      .item-show-comment__button
        コメントする
        
  .item-show-content__nav
    .item-nav-prev
      -unless @nav_prev == []
        = fa_icon 'chevron-left'
        =link_to "#{@nav_prev[0].name}", item_path(@nav_prev[0].id)
    .item-nav-next
      -unless @nav_next == []
        =link_to "#{@nav_next[0].name}", item_path(@nav_next[0].id)
        = fa_icon 'chevron-right'

  .item-show-content__sns
    %ul.item-sns-box
      %li.item-sns-box__facebook
        =link_to "", "#"
        = fa_icon 'facebook-square'
      %li.item-sns-box__twitter
        =link_to "", "#"
        = fa_icon 'twitter'
      %li.item-sns-box__pinterest
        =link_to "", "#"
        = fa_icon 'pinterest'

  .item-show-head
    %h2.item-show-head__title
      =link_to "#{@item.user.nickname}さんのその他の商品", "#"
  
  .item-show-user-item
    -@user_items.each_with_index do |item, i|
      -if @user_items.length > 6
        -break if i == 6
      .items-show-box
        =link_to '', item_path(item.id)
        .items-show-box__photo
          =image_tag item.images[0].image.to_s
        .items-show-box__body
          %h3 
            =item.name
          .items-show-box__body__num
            .items-show-box__body__num__price
              ¥
              =item.price
            .items-show-box__body__num__like
              =fa_icon 'heart-o'
              0

  .item-show-head
    %h2.item-show-head__title
      =link_to "#{@item.category.name} (#{@item.category.parent.parent.name})その他の商品", "#"

  .item-show-user-item
    -@category_items.each_with_index do |item, i|
      -if @category_items.length > 6
        -break if i == 6
      .items-show-box
        =link_to '', item_path(item.id)
        .items-show-box__photo
          =image_tag item.images[0].image.to_s
        .items-show-box__body
          %h3 
            =item.name
          .items-show-box__body__num
            .items-show-box__body__num__price
              ¥
              =item.price
            .items-show-box__body__num__like
              =fa_icon 'heart-o'
              0




= render partial: 'layouts/footer'