config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions' ,
    omniauth_callbacks: 'users/omniauth_callbacks'
    }
  # Facebook側で認証情報が挿入されると、再度リダイレクトしてアプリケーションのコールバックメソッドに戻ります。
  # コールバックを実装する場合に最初に必要なのは、config/routes.rbを開いて、Omniauthコールバックを実装するコールバックをDeviseに伝えることです
  
  root 'items#index'

  resources :users, only: [:index, :edit, :show, :update] do  

    collection do
      get 'logout' 
    end
    member do
      get 'item_management'
      get 'card'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :profiles, only: [:edit,:update]

  resources :addresses, only: [:edit,:update]
  # get ‘addresses/update’ => ‘addresses#update’

  resources :items do
  collection do
    get 'get_category_children', defaults: { format: 'json' }
    get 'get_category_grandchildren', defaults: { format: 'json' }
    get 'get_size', defaults: { format: 'json' }
    get 'get_shipping', defaults: { format: 'json' }
  end
  member do
    get 'get_category_children', defaults: { format: 'json' }
    get 'get_category_grandchildren', defaults: { format: 'json' }
    get 'get_size', defaults: { format: 'json' }
    get 'get_shipping', defaults: { format: 'json' }
    get 'buy', to: 'items#buy'
    get 'detail', to: 'detail'
    post 'pay', to: 'items#pay'
  end
end

  resources :signup do 
    collection do
      get 'top'
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' 
      get 'done'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :authenticate_user!, only: [:new, :pay, :delete, :show]

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        #もし購入画面から登録されたら
        if session[:id] != ""
          redirect_to buy_item_path(session[:id])
          session[:id].clear
        else
          redirect_to action: 'show'
        end
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to card_user_path(current_user.id)
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
  
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
= render partial: 'layouts/header'
%nav.bread-crumbs
  %ul
    %li.itemscope
      - breadcrumb :credit
      = render "layouts/breadcrumbs"
= render partial: 'items/exhibit_btn'

.l-container-clearfix
  .payment-method-box
    .payment-method-box__title
      クレジットカード情報入力
    .payment-method-box__info
      = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
        .card-input-form
          .card-input-form__inner
            .card-input-form__number
              %label カード番号
              %span 必須
              = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            .card-input-form__card-image
              = image_tag "card-image.png"
            .card-input-form__expiration
              %label 有効期限
              %span 必須
              .card-input-form__expiration__select
                %select#exp_month{name: "exp_month", type: "text"}
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                %span 月
                %select#exp_year{name: "exp_year", type: "text"}
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                  %option{value: "2030"}30
                %span 年
            .card-input-form__security
              %label セキュリティコード
              %span 必須
              = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
            .card-input-form__text
              %span ?
              カード背面の番号とは？
            .card-input-form__btn
              #card_token
              = submit_tag "追加する", id: "token_submit"

  = render partial: 'users/side-bar'
= render partial: 'layouts/footer'

app/views/card/show.html.haml
= render partial: 'layouts/header'
%nav.bread-crumbs
  %ul
    %li.itemscope
      - breadcrumb :payment
      = render "layouts/breadcrumbs"
= render partial: 'items/exhibit_btn'
      
.l-container-clearfix
  .payment-method-box
    .payment-method-box__title
      支払い方法
    .payment-method-box__register
      .payment-method-box__register__title
        クレジットカード一覧

      .payment-method-box__register__list
        = image_tag "visa.png"
        .payment-method-box__register__list__num
          = "**** **** **** " + @default_card_information.last4

        .payment-method-box__register__list__expiration
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
      
        = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button 削除する

      .payment-method-box__register__about
        =link_to '支払い方法について', '#'
        = fa_icon 'chevron-right'

        
  
  = render partial: 'users/side-bar'
= render partial: 'layouts/footer'