config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions' ,
    omniauth_callbacks: 'users/omniauth_callbacks'
    }
  # Facebook側で認証情報が挿入されると、再度リダイレクトしてアプリケーションのコールバックメソッドに戻ります。
  # コールバックを実装する場合に最初に必要なのは、config/routes.rbを開いて、Omniauthコールバックを実装するコールバックをDeviseに伝えることです
  
  root 'items#index'

  resources :users, only: [:index, :edit, :show, :update] do  

    collection do
      get 'logout' 
    end
    member do
      get 'item_management'
      get 'card'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :profiles, only: [:edit,:update]

  resources :addresses, only: [:edit,:update]
  # get ‘addresses/update’ => ‘addresses#update’

  resources :items do
  collection do
    get 'get_category_children', defaults: { format: 'json' }
    get 'get_category_grandchildren', defaults: { format: 'json' }
    get 'get_size', defaults: { format: 'json' }
    get 'get_shipping', defaults: { format: 'json' }
  end
  member do
    get 'get_category_children', defaults: { format: 'json' }
    get 'get_category_grandchildren', defaults: { format: 'json' }
    get 'get_size', defaults: { format: 'json' }
    get 'get_shipping', defaults: { format: 'json' }
    get 'buy', to: 'items#buy'
    get 'detail', to: 'detail'
    post 'pay', to: 'items#pay'
  end
end

  resources :signup do 
    collection do
      get 'top'
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' 
      get 'done'
    end
  end
end

app/views/layouts/_breadcrumbs.html.haml
= breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-list"

app/views/layouts/_footer.html.haml
.footer-image-box
  = image_tag "footer-image.png", class: "footer-image"
.footer
  .footer__overview
    .overview-field
      %h2 メルカリについて
      %ul.overview-field-detail
        %li.overview-detail
          =link_to '会社概要 (運営会社)', '#'
        %li.overview-detail
          =link_to '採用情報', '#'
        %li.overview-detail
          =link_to 'プレスリリース', '#'
        %li.overview-detail
          =link_to '公式ブログ', '#'
        %li.overview-detail
          =link_to 'メルカリロゴ利用ガイドライン', '#'
        .footer-icon-box
          =link_to ("https://twitter.com/mercari_jp") do
            = fa_icon 'twitter', class: 'footer-sns-logo'
          =link_to  ("https://www.facebook.com/mercarijp") do
            = fa_icon 'facebook-square', class: 'footer-sns-logo'
    .overview-field
      %h2 ヘルプ＆ガイド
      %ul.overview-field-detail
        %li.overview-detail
          =link_to 'メルカリガイド', '#'
        %li.overview-detail
          =link_to 'らくらくメルカリ便', '#'
        %li.overview-detail
          =link_to 'ゆうゆうメルカリ便', '#'
        %li.overview-detail
          =link_to '大型メルカリ便', '#'
        %li.overview-detail
          =link_to '車体取引ガイド', '#'
        %li.overview-detail
          =link_to 'メルカリあんしん・あんぜん宣言！', '#'
        %li.overview-detail
          =link_to '偽ブランド品撲滅への取り組み', '#'
        %li.overview-detail
          =link_to 'メルカリボックス', '#'
    .overview-field
      %h2 プライバシーと利用規約
      %ul.overview-field-detail2
        %li.overview-detail
          =link_to 'プライバシーポリシー', '#'
        %li.overview-detail
          =link_to 'メルカリ利用規約', '#'
        %li.overview-detail
          =link_to 'あんしんスマホサポート制度に関する利用特約', '#'
        %li.overview-detail
          =link_to 'コンプライアンスポリシー', '#'
      %ul.overview-field-detail3
        %li.overview-detail
          =link_to '個人データの安全管理に係る基本方針', '#'
        %li.overview-detail
          =link_to '特定商取引に関する表記', '#'
        %li.overview-detail
          =link_to '資金決済法に基づく表示', '#'
        %li.overview-detail
          =link_to '法令順守と犯罪抑止のために', '#'
    .overview-field
      %h2 国
      %ul.overview-field-detail
        %li.overview-detail
          =link_to '日本', '#'
        %li.overview-detail
          =link_to 'United States', '#'
  .footer-last
    =image_tag "footer-logo.png",class: "footer-mercari-logo"
    .footer-last-name 
      %p © 2019 Mercari

app/views/layouts/_header.html.haml
.header
  .header-box
    .header-box__top 
      .logo-box
        =link_to "", items_path
        = image_tag "mercari.png",size: "132x35"
      .search-box
        %input.search-box__input-field{placeholder: '何かお探しですか？'}
        .serach-box__btn
          =fa_icon "search"
    - if user_signed_in?
      .header-box__under
        %ul.header-box__under__left
          %li.category-box
            =fa_icon "list-ul"
            %span カテゴリーから探す
          %li.brand-box
            = image_tag "brand-logo.png", size: "18x13"
            %span ブランドから探す
  
        %ul.header-box__under__right
  
          %li.pc-header-user-nav
            = link_to "#", class: "pc-header-menu-link" do
              = fa_icon "bell-o", class: :mypage_icon
              %span お知らせ
  
          %li.sign-in-box
            = link_to "#", class: "pc-header-menu-link" do
              = fa_icon "check", class: :mypage_icon
              %span やることリスト
  
          %li.my-page-box
            = link_to user_path(current_user.id), class: "pc-header-user-icon" do
              %figure
                =image_tag "user_icon.jpg", size: "32x32"
              %span マイページ
    - else
      .header-box__under
        %ul.header-box__under__left
          %li.category-box
            =fa_icon "list-ul"
            %span カテゴリーから探す
          %li.brand-box
            = image_tag "brand-logo.png", size: "18x13"
            %span ブランドから探す
        %ul.header-box__under__right
          %li.sign-in-box
            .sign-in-box__btn
              =link_to '新規会員登録', top_signup_index_path
          %li.log-in-box
            .log-in-box__btn
              =link_to 'ログイン',  user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FreemarketSample57b
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}
  %body
    = yield